# Generated by Django 3.1.2 on 2021-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=10)),
                ('sub_type', models.CharField(max_length=10)),
                ('teamone', models.CharField(max_length=50)),
                ('teamtwo', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('toss_winner_team', models.CharField(max_length=50)),
                ('winner_team', models.CharField(max_length=50)),
            ],
        ),
    ]
