# Generated by Django 3.1.2 on 2021-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20210407_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sub_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
