# Generated by Django 3.1.2 on 2021-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_auto_20210407_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='description',
            new_name='scoreone',
        ),
        migrations.AddField(
            model_name='match',
            name='elected',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='man_of_the_match',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='scoretwo',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
